import { Router, type IRouter } from "express";
import healthRouter from "./health";
import csrfRouter from "./csrf";
import subjectsRouter from "./subjects";
import chaptersRouter from "./chapters";
import topicsRouter from "./topics";
import progressRouter from "./progress";
import examsRouter from "./exams";
import storageRouter from "./storage";
import pomodoroRouter from "./pomodoro";
import tasksRouter from "./tasks";
import externalTestsRouter from "./external-tests";
import adminRouter from "./admin";
import dashboardRouter from "./dashboard";
import notificationsRouter from "./notifications";
import pushRouter from "./push";
import authEmailRouter from "./auth-email";
import userRouter from "./user";
import questionsRouter from "./questions";
import searchRouter from "./search";
import announcementsRouter from "./announcements";
import testManagementRouter from "./test-management";

const router: IRouter = Router();

router.use(healthRouter);
router.use(csrfRouter);
router.use(announcementsRouter);
router.use(questionsRouter);
router.use(searchRouter);
router.use(dashboardRouter);
router.use(subjectsRouter);
router.use(chaptersRouter);
router.use(topicsRouter);
router.use(progressRouter);
router.use(examsRouter);
router.use(storageRouter);
router.use(pomodoroRouter);
router.use(tasksRouter);
router.use(externalTestsRouter);
router.use(adminRouter);
router.use(testManagementRouter);
router.use(notificationsRouter);
router.use(pushRouter);
router.use(authEmailRouter);
router.use(userRouter);

export default router;
